LearningPlatform.mvc/Areas/Admin/Controllers/CourseController.cs
using LearningPlatform.BLL.ViewModels;
using LearningPlatform.DAL.DB;
using LearningPlatform.DAL.Entities;
using LearningPlatform.DAL.Repository.Abstraction;
using LearningPlatform.DAL.Repository.Impelementation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LearningPlatform.mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CourseController : Controller
    {
        private IUnitOfWork _unitOfWork; 
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CourseController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

		public IActionResult Index(string searchTerm)
        {

            var categories = _unitOfWork.Course.GetAll(Includeword:"Category");
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            CourseVM courseVM = new CourseVM()
            {
                Course = new Course(),
                CategoryList = _unitOfWork.Category.GetAll().Select(x=> new SelectListItem
                {
                    Text = x.CategoryName,
                    Value = x.Id.ToString()
                })
            };
            return View(courseVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CourseVM courseVM,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, @"Images\Courses");
                    var ext = Path.GetExtension(file.FileName);
                    using (var filestream = new FileStream(Path.Combine(Upload, filename + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream); 
                    }
                    courseVM.Course.Image = @"Images\Courses\" + filename + ext;
                }

                _unitOfWork.Course.Add(courseVM.Course);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            return View(courseVM.Course);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null | id == 0)
            {
                NotFound();
            }
            //var category = _context.Categories.Find(id);

			CourseVM courseVM = new CourseVM()
			{
				Course = _unitOfWork.Course.GetFirstorDefault(x => x.Id == id),
				CategoryList = _unitOfWork.Category.GetAll().Select(x => new SelectListItem
				{
					Text = x.CategoryName,
					Value = x.Id.ToString()
				})
			};
			return View(courseVM);
        }
        [HttpPost]
        public IActionResult Edit(CourseVM courseVM,IFormFile? file)
        {
            if (ModelState.IsValid)
            {
				string RootPath = _webHostEnvironment.WebRootPath;
				if (file != null)
				{
					string filename = Guid.NewGuid().ToString();
					var Upload = Path.Combine(RootPath, @"Images\Courses");
					var ext = Path.GetExtension(file.FileName);

                    if (courseVM.Course.Image != null)
                    {
                        var oldImg = Path.Combine(RootPath,courseVM.Course.Image.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImg))
                        {
                            System.IO.File.Delete(oldImg);
                        }
                    }

					using (var filestream = new FileStream(Path.Combine(Upload, filename + ext), FileMode.Create))
					{
						file.CopyTo(filestream);
					}
					courseVM.Course.Image = @"Images\Courses\" + filename + ext;
				}


				//_context.Categories.Update(category);
				//_context.SaveChanges();
				_unitOfWork.Course.Update(courseVM.Course);
                _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            return View(courseVM.Course);
        }



        [HttpPost]
        public IActionResult DeleteCourse(int id)
        {
            var course = _unitOfWork.Course.GetFirstorDefault(x => x.Id == id);           
            _unitOfWork.Course.Remove(course);
            var oldImg = Path.Combine(_webHostEnvironment.WebRootPath, course.Image.TrimStart('\\'));
            if (System.IO.File.Exists(oldImg))
            {
                System.IO.File.Delete(oldImg);
            }

            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }
        



    }
}

LearningPlatform.mvc/Areas/Admin/Controllers/DashboardController.cs
using LearningPlatform.DAL.DB;
using LearningPlatform.DAL.Repository.Abstraction;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LearningPlatform.mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly LearningPlatformDbContext _context;
        private readonly IOrderRepository _orderRepository;

        public DashboardController(IUnitOfWork unitOfWork, IOrderRepository orderRepository, LearningPlatformDbContext context)
        {
            _unitOfWork = unitOfWork;
            _orderRepository = orderRepository;
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.CoursesCount = _unitOfWork.Course.GetAll().Count();
            ViewBag.UsersCount = _context.ApplicationUsers.ToList().Count();
            ViewBag.OrdersCount = _context.Orders.ToList().Count();
            ViewBag.Category = _unitOfWork.Category.GetAll().Count();

            /*var lastSixOrders = _context.Orders
			.Include(x => x.OrderItems)
			.ThenInclude(x => x.Course)
			.Include(x => x.User)
			.OrderByDescending(x => x.Id)
            .Take(6)*/
            var lastSixOrders = _orderRepository.GetAllOrders()
            .OrderByDescending(x => x.Id)
			.Take(6)
			.ToList();
            return View(lastSixOrders);
        }
    }
}

LearningPlatform.mvc/Areas/Admin/Controllers/UsersController.cs
using LearningPlatform.BLL.Utilities;
using LearningPlatform.DAL.DB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LearningPlatform.mvc.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = "Admin")]
	public class UsersController : Controller
	{
		private readonly LearningPlatformDbContext _context;

		public UsersController(LearningPlatformDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var result = (ClaimsIdentity)User.Identity;
			var claim = result.FindFirst(ClaimTypes.NameIdentifier);
			string userid = claim.Value;
			return View(_context.ApplicationUsers.Where(x=>x.Id != userid).ToList());
		}
        public IActionResult LockUnlock(string? id)
        {
            var user = _context.ApplicationUsers.FirstOrDefault(x => x.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            if (user.LockoutEnd == null || user.LockoutEnd < DateTime.Now)
            {
                user.LockoutEnd = DateTime.Now.AddYears(1);
            }
            else
            {
                user.LockoutEnd = DateTime.Now;
            }
            _context.SaveChanges();
            return RedirectToAction("Index", "Users", new { area = "Admin" });
        }
        public IActionResult Delete(string? id)
        {
            var user = _context.ApplicationUsers.FirstOrDefault(x => x.Id == id);
            _context.ApplicationUsers.Remove(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

LearningPlatform.mvc/Areas/User/Controllers/HomeController.cs
using LearningPlatform.BLL.ViewModels;
using LearningPlatform.DAL.Entities;
using LearningPlatform.DAL.Repository.Abstraction;
using LearningPlatform.DAL.Repository.Impelementation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LearningPlatform.mvc.Areas.User.Controllers
{
    [Area("User")]
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

		public HomeController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public IActionResult Courses()
		{
			var categories = _unitOfWork.Category.GetAll();
			var courses = _unitOfWork.Course.GetAll();
			var viewModel = new CourseViewModel
			{
				Categories = categories,
				Courses = courses
			};
			
			return View(viewModel);
		}
		public IActionResult Index()
		{
			var categories = _unitOfWork.Category.GetAll();
			var courses = _unitOfWork.Course.GetAll().Take(8);
			var trendingCourse = _unitOfWork.Course.TrendingCourse();
			var viewModel = new CourseViewModel
			{
				Categories = categories,
				Courses = courses,
				TrendingCourse = trendingCourse
			};
			return View(viewModel);
		}
		public IActionResult Details(int id)
		{
			var result = _unitOfWork.Course.GetFirstorDefault(x => x.Id == id, Includeword: "Category");

			return View(result);
		}
        public IActionResult Category(int categoryId)
		{
			var courses = _unitOfWork.Course.GetAll(x => x.CategoryId == categoryId).Select(item => new
			{
				item.Id,
				item.CourseName,
				item.CourseDescription,
				item.Image,
				item.CourseTime,
				item.TotalLecture,
				item.Price,
				Level = item.Level.ToString(),
				ImageUrl = Url.Content("/" + item.Image) 
			});
			return Json(courses);
		}
		public IActionResult GetAllCourses()
		{
			var allcourses= _unitOfWork.Course.GetAll().Take(8).Select(item => new
			{
				item.Id,
				item.CourseName,
				item.CourseDescription,
				item.Image,
				item.CourseTime,
				item.TotalLecture,
				item.Price,
				Level = item.Level.ToString(),
				ImageUrl = Url.Content("/" + item.Image)
			});
			return Json(allcourses);
		}

	}
}

LearningPlatform.mvc/Areas/User/Controllers/OrderController.cs
using LearningPlatform.DAL.Cart;
using LearningPlatform.DAL.Repository.Abstraction;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LearningPlatform.mvc.Areas.User.Controllers
{
	[Area("User")]
    [Authorize]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly ShoppingCart _shoppingCart;
		private readonly IOrderRepository _orderRepository;

		public OrderController(IUnitOfWork unitOfWork, ShoppingCart shoppingCart, IOrderRepository orderRepository)
		{
			_unitOfWork = unitOfWork;
			_shoppingCart = shoppingCart;
			_orderRepository = orderRepository;
		}
		public ActionResult Index()
		{
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			string roleId = User.FindFirstValue(ClaimTypes.Role);
			var order = _orderRepository.GetOrderAndRoleByUserId(userId,roleId);
			return View(order);
		}
		public IActionResult ShoppingCart()
		{
			var item = _shoppingCart.GetShoppingCartItems();
			ViewBag.Total = _shoppingCart.GetShoppingCartTotal();
			return View(item);
		}

        public IActionResult AddToCart(int id)
        {
            var item = _unitOfWork.Course.GetFirstorDefault(x => x.Id == id);
            if (item != null)
            {
                _shoppingCart.AddItemToShoppingCart(item);
            }
            return RedirectToAction("ShoppingCart");
        }
        public IActionResult RemoveFromCart(int id)
        {
            var item = _unitOfWork.Course.GetFirstorDefault(x => x.Id == id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromShoppingCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
		public IActionResult CompleteOrder()
		{
			var items = _shoppingCart.GetShoppingCartItems();
			string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			_orderRepository.StoredOrders(items, userId);
			_shoppingCart.ClearShoppingCart();
			return View("CompleteOrder");
		}



	}
}

LearningPlatform.mvc/Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>

<html>
<head>
	<title>Eduport</title>

	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>@ViewData["Title"] - Eduport</title>
	<!-- Favicon -->
	<link rel="shortcut icon" href="~/assets/images/favicon.ico">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap">

	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/font-awesome/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/apexcharts/css/apexcharts.css">

	<!-- Theme CSS -->
	<link id="style-switch" rel="stylesheet" type="text/css" href="~/assets/css/style.css">

</head>
<body>
	<partial name="_HeaderPartialcshtml" />
	
	<!-- **************** MAIN CONTENT START **************** -->
	<main>

		<!-- Page content START -->
		<section class="pt-0">
			<div class="container">
				<div class="row">
					<!-- Right sidebar START -->
					<div class="col-xl-3" >
						<!-- Responsive offcanvas body START -->
						<nav class="navbar navbar-light navbar-expand-xl mx-0">
							<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
								<!-- Offcanvas header -->
								<div class="offcanvas-header bg-light">
									<h5 class="offcanvas-title" id="offcanvasNavbarLabel">My profile</h5>
									<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
								</div>
								<!-- Offcanvas body -->
								<div class="offcanvas-body p-3 p-xl-0" style="height: 541px;">
									<div class="bg-dark border rounded-3 pb-0 p-3 w-100">
										<!-- Dashboard menu -->
										<div class="list-group list-group-dark list-group-borderless">
											<a class="list-group-item active" asp-action="Index" asp-controller="Dashboard" ><i class="bi bi-ui-checks-grid fa-fw me-2"></i>Dashboard</a>
											<a class="list-group-item"  asp-action="Index" asp-controller="Course" ><i class="bi bi-basket fa-fw me-2"></i>All Courses</a>
											<a class="list-group-item" asp-action="Index" asp-controller="Category"><i class="bi bi-basket fa-fw me-2"></i>All Categoies</a>
											<a class="list-group-item" asp-action="Index" asp-controller="Users" ><i class="bi bi-people fa-fw me-2"></i>All Students</a>
											<a class="list-group-item" asp-action="Index" asp-controller="Order" ><i class="bi bi-folder-check fa-fw me-2"></i>All Orders</a>

										</div>
									</div>
								</div>
							</div>
						</nav>
						<!-- Responsive offcanvas body END -->
					</div>
					<!-- Right sidebar END -->
					<!-- Main content START -->
					<div class="col-xl-9">
						@RenderBody()
				</div><!-- Row END -->
			</div>
		</section>
		<!-- =======================
		Page content END -->

	</main>
	<!-- **************** MAIN CONTENT END **************** -->
	<!-- =======================
	Footer START -->
	<footer class="bg-dark p-3">
		<div class="container">
			<div class="row align-items-center">
				<!-- Widget -->
				<div class="col-md-4 text-center text-md-start mb-3 mb-md-0">
					<!-- Logo START -->
					<a href="index.html"> <img class="h-20px" src="~/assets/images/logo-light.svg" alt="logo"> </a>
				</div>

				<!-- Widget -->
				<div class="col-md-4 mb-3 mb-md-0">
					<div class="text-center text-white">
						Copyrights ©2024 <a href="#" class="text-reset btn-link">Eduport</a>. All rights reserved.
					</div>
				</div>
				<!-- Widget -->
				<div class="col-md-4">
					<!-- Rating -->
					<ul class="list-inline mb-0 text-center text-md-end">
						<li class="list-inline-item ms-2"><a href="#"><i class="text-white fab fa-facebook"></i></a></li>
						<li class="list-inline-item ms-2"><a href="#"><i class="text-white fab fa-instagram"></i></a></li>
						<li class="list-inline-item ms-2"><a href="#"><i class="text-white fab fa-linkedin-in"></i></a></li>
						<li class="list-inline-item ms-2"><a href="#"><i class="text-white fab fa-twitter"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- =======================
	Footer END -->
	<!-- Back to top -->
	<div class="back-top"><i class="bi bi-arrow-up-short position-absolute top-50 start-50 translate-middle"></i></div>

	<!-- Bootstrap JS -->
	<script src="assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	<!-- Vendors -->
	<script src="assets/vendor/purecounterjs/dist/purecounter_vanilla.js"></script>
	<script src="assets/vendor/apexcharts/js/apexcharts.min.js"></script>

	<!-- Template Functions -->
	<script src="assets/js/functions.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LearningPlatform.mvc/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>

<html>
	<head>
	<title>@ViewData["Title"] - Eduport</title>

		<!-- Meta Tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="author" content="Webestica.com">
		<meta name="description" content="Eduport- LMS, Education and Course Theme">

		<!-- Favicon -->
		<link rel="shortcut icon" href="assets/images/favicon.ico">

		<!-- Google Font -->
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap">

		<!-- Plugins CSS -->
		<link rel="stylesheet" type="text/css" href="~/assets/vendor/font-awesome/css/all.min.css">
		<link rel="stylesheet" type="text/css" href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css">

		<!-- Theme CSS -->
		<link id="style-switch" rel="stylesheet" type="text/css" href="~/assets/css/style.css">


	</head>
<body>
        @RenderBody()
	@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

LearningPlatform.mvc/Views/Shared/_HeaderPartialcshtml.cshtml
<header class="navbar-light navbar-sticky header-static">
	<!-- Logo Nav START -->
	<nav class="navbar navbar-expand-xl">
		<div class="container-fluid px-3 px-xl-5">
			<!-- Logo START -->
			<a class="navbar-brand" href="/User/Home/Index">
				<img class="light-mode-item navbar-brand-item" src="~/assets/images/logo.svg" alt="logo">
				<img class="dark-mode-item navbar-brand-item" src="~/assets/images/logo-light.svg" alt="logo">
			</a>
			<!-- Logo END -->
			<!-- Responsive navbar toggler -->
			<button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-animation">
					<span></span>
					<span></span>
					<span></span>
				</span>
			</button>

			<!-- Main navbar START -->
			<div class="navbar-collapse collapse" id="navbarCollapse">

				<!-- Nav category menu START -->
				<ul class="navbar-nav navbar-nav-scroll me-auto">
					<!-- Nav item 1 Demos -->

				</ul>
				<!-- Nav category menu END -->
				<!-- Nav Main menu START -->
				<ul class="navbar-nav navbar-nav-scroll me-auto">
					@if (User.Identity.IsAuthenticated)
					{
						@if (User.IsInRole("Admin"))
						{
							<a class="nav-link" href="~/Admin/Dashboard">Dashboard</a>
						}
						else
						{
							<a class="nav-link" href="~/User/Home/Courses">All Courses</a>
							<a class="nav-link" href="~/User/Order">My orders</a>
						}
					}

				</ul>
				<!-- Nav Main menu END -->
				<!-- Nav Search START -->

				<!-- Nav Search END -->
			</div>
			<!-- Main navbar END -->
			<!-- Profile START -->
			<partial name="_LoginPartial" />
			@await Component.InvokeAsync("ShoppingCartSummary")
			<!-- Profile START -->
		</div>
	</nav>
	<!-- Logo Nav END -->
</header>

LearningPlatform.mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearningPlatform.mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LearningPlatform.mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LearningPlatform.mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LearningPlatform.mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LearningPlatform.mvc/Views/Shared/_User.cshtml
<!DOCTYPE html>

<html>
<head>
	<title>@ViewData["Title"] - Eduport</title>

	<!-- Meta Tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Favicon -->
	<link rel="shortcut icon" href="~/assets/images/favicon.ico">

	<!-- Google Font -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap">

	<!-- Plugins CSS -->
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/font-awesome/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css">
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/tiny-slider/tiny-slider.css">
	<link rel="stylesheet" type="text/css" href="~/assets/vendor/glightbox/css/glightbox.css">

	<!-- Theme CSS -->
	<link  rel="stylesheet" type="text/css" href="~/assets/css/style.css">

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-7N7LGGGWT1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag() { dataLayer.push(arguments); }
		gtag('js', new Date());

		gtag('config', 'G-7N7LGGGWT1');
	</script>

</head>
<body>
	<partial name="_HeaderPartialcshtml" />
        @RenderBody()
	<!-- Bootstrap JS -->
	<script src="~/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	<!-- Vendors -->
	<script src="~/assets/vendor/tiny-slider/tiny-slider.js"></script>
	<script src="~/assets/vendor/glightbox/js/glightbox.js"></script>
	<script src="~/assets/vendor/purecounterjs/dist/purecounter_vanilla.js"></script>

	<!-- Template Functions -->
	<script src="~/assets/js/functions.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>